---
title: "P8105_hw6_nk3037"
author: "Navya Koneripalli"
date: "2023-11-28"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Question 2
### Setup
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
# Initial linear model
lin_model = lm(tmax ~ tmin + prcp, data = weather_df)

# Bootstrap sample
num_samples = 5000

# Creating a matrix for the estimates
bootstrap_estimates = matrix(NA, nrow = num_samples, ncol = 2)

# Bootstrapping
for (i in 1:num_samples) {
  bootstrap_sample = weather_df[sample(nrow(weather_df), replace = TRUE), ]
  bootstrap_model = lm(tmax ~ tmin + prcp, data = bootstrap_sample)
  bootstrap_estimates[i, 1] = broom::glance(bootstrap_model)$r.squared
  bootstrap_estimates[i, 2] = sum(broom::tidy(bootstrap_model)$estimate[-1])
}

# Plotting the distribution
hist(bootstrap_estimates[, 1], main = "Distribution of r^2", xlab = "r^2")
hist(bootstrap_estimates[, 2], main = "Distribution of log(hat(β1) * hat(β2))", xlab = "log(β1*β2)")

```

